export const GENRES = [
  "Podcasts",
  "Romance",
  "Relax",
  "Work Out",
  "Feel Good",
  "Energise",
  "Sad",
  "Commute",
  "Party",
  "Focus",
  "Sleep",
];

export const SONGS = [
  {
    id: 1,
    title: "Song 1 this is long title",
    artist: "Artist 1",
    genre: "Podcasts",
    plays: 1300000000,
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
  },
  {
    id: 2,
    title: "Song 2 this is little longer title",
    artist: "Artist 2 same for artist",
    genre: "Romance",
    plays: 4000000,
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
  },
  {
    id: 3,
    title: "Song 3 this is too long title (Album Version Explicit)",
    artist: "Artist 3",
    genre: "Relax",
    plays: 1000000,
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
  },
  {
    id: 4,
    title: "Song 4",
    artist: "Artist 4",
    genre: "Work Out",
    plays: 1000000,
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
  },
  {
    id: 5,
    title: "Song 5",
    artist: "Artist 5",
    genre: "Feel Good",
    plays: 1000000,

    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
  },
  {
    id: 6,
    title: "Song 6",
    artist: "Artist 6",
    genre: "Energise",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 50000000,
  },
  {
    id: 7,
    title: "Song 7",
    artist: "Artist 7",
    genre: "Sad",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 8,
    title: "Song 8",
    artist: "Artist 8",
    genre: "Commute",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 9,
    title: "Song 9",
    artist: "Artist 9",
    genre: "Party",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 10,
    title: "Song 10",
    artist: "Artist 10",
    genre: "Focus",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 6000000,
  },
  {
    id: 11,
    title: "Song 11",
    artist: "Artist 11",
    genre: "Sleep",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 12,
    title: "Song 12",
    artist: "Artist 12",
    genre: "Podcasts",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 13,
    title: "Song 13",
    artist: "Artist 13",
    genre: "Romance",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 14,
    title: "Song 14",
    artist: "Artist 14",
    genre: "Relax",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 15,
    title: "Song 15",
    artist: "Artist 15",
    genre: "Work Out",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 16,
    title: "Song 16",
    artist: "Artist 16",
    genre: "Feel Good",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 17,
    title: "Song 17",
    artist: "Artist 17",
    genre: "Energise",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 18,
    title: "Song 18",
    artist: "Artist 18",
    genre: "Sad",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },
  {
    id: 19,
    title: "Song 19",
    artist: "Artist 19",
    genre: "Commute",
    image: require("../assets/images/songs/tu-hai-kahan.jpeg"),
    plays: 1000000,
  },

];
